### ISSUE TITLE
Approvals & Allowances Consistency

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/rebasing-ibbtc#4]
The `_allowances` mapping needs to track shares, similar to how the `_balances` mapping tracks shares

**Reference issues**
* [17](https://github.com/code-423n4/2021-10-badgerdao-findings/issues/17)

**Comment by tabshaikh** [comment]
similar findings: 
https://github.com/code-423n4/2021-10-badgerdao-findings/issues/63
https://github.com/code-423n4/2021-10-badgerdao-findings/issues/43
https://github.com/code-423n4/2021-10-badgerdao-findings/issues/17
